server:
  port: 8080
spring:
  ## 数据库配置
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:p6spy:mysql://127.0.0.1:3306/project?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&tinyInt1isBit=false&serverTimezone=Asia/Shanghai&useSSL=true
    username: root
    password: root
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    hikari:
      connection-test-query: select 'x'
      idle-timeout: 60000
      maximum-pool-size: 100
      minimum-idle: 5
  ## redis配置
  redis:
    host: localhost
    port: 6379
    timeout: 30s
    database: 8
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    listener:
      simple:
        prefetch: 1
        acknowledge-mode: manual
        max-concurrency: 10
        retry:
          initial-interval: 10000
          enabled: true
          max-interval: 30000
    ## 移动端和管理后台要分区创建mq
    virtual-host: /manage

system:
  # 全局配置
  upload-dir: D://file
  # 管理后台配置
  manage:
    token:
      jwt-secret: xC&ln9Q5pNn11RXUr7s#Owzm4nK16wGB3PTnM6OI@b51Q9NUrQTrTIQU6r&UTT9O
      mock-token: 7cfbe8365034496aa4385009bf827d22
  # 支付宝支付配置
  ali-pay:
    notify-host: https://localhost:8080
  # 微信小程序 公众号 微信支付配置
  wechat:
    notify-host: https://localhost:8080
    mini-version: trial
  # 系统环境
  env: dev
