## tomcat配置
server:
  servlet:
    session:
      timeout: 1800s
  tomcat:
    uri-encoding: UTF-8
## spring应用上下文配置
spring:
  application:
    name: manage
  profiles:
    ## 环境切换
    active: dev
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 500MB
  main:
    web-application-type: servlet
  jackson:
    time-zone: GMT+8
  ## freemarker配置
  freemarker:
    suffix: .ftl
    ## freemarker内置参数设置
    settings:
      template_update_delay: 60s
      number_format: 0.##
      default_encoding: UTF-8
      output_encoding: UTF-8
      url_escaping_charset: UTF-8
      locale: zh_CN
      time_format: HH:mm:ss
      date_format: yyyy-MM-dd
      datetime_format: yyyy-MM-dd HH:mm:ss
    template-loader-path: classpath:/templates/,file:////usr/local/template
    cache: true
    charset: UTF-8
    check-template-location: false
    content-type: text/html
## mybatis-plus配置
mybatis-plus:
  mapper-locations:
    - classpath*:mapper/**/*.xml
  type-aliases-package: com.eghm.model.dto;com.eghm.model.vo
  configuration:
    map-underscore-to-camel-case: true

system:
  manage:
    security:
      skip-auth:
        - /captcha
        - /**/captcha
        - /doc.html
        - /webjars/**
        - /v2/api-docs
        - /swagger-resources/**
        - /manage/login
        - /favicon.ico
        - /manage/export/exportMenu
