server:
  port: 10086
spring:
  ## 数据库配置
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:p6spy:mysql://127.0.0.1:3306/base_project?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&tinyInt1isBit=false&serverTimezone=Asia/Shanghai&useSSL=true
    username: root
    password: root
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    hikari:
      connection-test-query: select 'x'
      idle-timeout: 60000
      maximum-pool-size: 100
      minimum-idle: 5
  ## redis配置
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 30s
      database: 5
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    listener:
      simple:
        prefetch: 1
        acknowledge-mode: manual
        max-concurrency: 10
        retry:
          initial-interval: 10000
          enabled: true
          max-interval: 30000

system:
  # 全局文件上传路径
  upload-path: D://file
  # 管理后台配置
  manage:
    token:
      # 模拟token方便调试(可在redis设置永久有效)
      mock-token: 1fc33b2a04fb4573b51b5a7a56c13678
  # 微信小程序 公众号 微信支付配置
  wechat:
    ma:
      version: trial
    pay:
      notify-host: https://localhost:8080
  # 系统环境
  env: dev
