server:
  port: 8080
spring:
  ## 数据库配置
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:log4jdbc:mysql://127.0.0.1:3306/project?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&tinyInt1isBit=false&serverTimezone=UTC&useSSL=true
    username: root
    password: root
    driver-class-name: net.sf.log4jdbc.DriverSpy
    hikari:
      connection-test-query: select 'x'
      idle-timeout: 60000
      maximum-pool-size: 100
      minimum-idle: 5
  ## redis配置
  redis:
    host: localhost
    port: 6379
    timeout: 30s
    database: 8

## 自定义系统配置
application:
  ## 未登陆时,不需要拦截的url AntPathRequestMatcher匹配规则
  ignore-url:
    - /
    - /index
    - /captcha
    - /**/captcha
  ## 项目版本号
  version: 0.6.1
  ## 登陆后不需要拦截的url AntPathRequestMatcher匹配规则
  login-ignore-url:
    - /main
    - /portal
    - /upload
  # 是否开启定时任务
  job: true