server:
  port: 8080
spring:
  ## 数据库配置
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:log4jdbc:mysql://127.0.0.1:3306/project?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&tinyInt1isBit=false&serverTimezone=UTC&useSSL=true
    username: root
    password: root
    driver-class-name: net.sf.log4jdbc.DriverSpy
    hikari:
      connection-test-query: select 'x'
      idle-timeout: 60000
      maximum-pool-size: 100
      minimum-idle: 5
  ## redis配置
  redis:
    host: localhost
    port: 6379
    timeout: 30s
    database: 8
  ## mq配置
  rabbitmq:
    host: devk8s.lishicloud.com
    port: 32024
    listener:
      simple:
        prefetch: 1
        acknowledge-mode: auto
        max-concurrency: 10
    username: lishi
    password: lishi@123456

system:
  upload-dir: D://file
  base-package: com.eghm.web.controller
  job-enable: true
  manage:
    security:
      ignore:
        - /captcha
        - /**/captcha
        - /doc.html
        - /webjars/**
        - /v2/api-docs
        - /swagger-resources/**
      ignore-auth:
        # 占坑而已
        - /homeResource
    jwt:
      secret-key: xC&ln9Q5pNn11RXUr7s#Owzm4nK16wGB3PTnM6OI@b51Q9NUrQTrTIQU6r&UTT9O

