server:
  port: 9090
spring:
  redis:
    host: 127.0.0.1
    port: 6379
    timeout: 30s
    database: 8
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:p6spy:mysql://127.0.0.1:3306/project?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC&tinyInt1isBit=false
    username: root
    password: root
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    hikari:
      connection-test-query: select 'X'
      maximum-pool-size: 100
      minimum-idle: 5
  mail:
    host: smtp.qq.com
    password: lxshegkzfvnjbgah
    username: ergehenmeng@qq.com
    properties:
      mail.from: ergehenmeng@qq.com
  rabbitmq:
    listener:
      simple:
        prefetch: 1
        acknowledge-mode: auto
        max-concurrency: 10
system:
  ali-pay:
    notify-host: https://localhost:8080
    pay-notify-url: /notify/ali/pay
    refund-notify-url: /notify/ali/refund
  wechat:
    notify-host: https://localhost:8080
    pay-notify-url: /notify/weChat/pay
    refund-notify-url: /notify/weChat/refund