server:
  port: 9090
spring:
  main:
    web-application-type: servlet
  application:
    name: api
    # 静态资源配置
  mvc:
    throw-exception-if-no-handler-found: true
    # redis配置
  redis:
    host: 127.0.0.1
    port: 6379
    timeout: 30s
    database: 8
    # mysql配置
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:p6spy:mysql://127.0.0.1:3306/project?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC&tinyInt1isBit=false
    username: root
    password: root
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    hikari:
      connection-test-query: select 'X'
      maximum-pool-size: 100
      minimum-idle: 5
  freemarker:
    check-template-location: false
    content-type: text/html
    settings:
      number_format: 0.##
      default_encoding: UTF-8
      output_encoding: UTF-8
      url_escaping_charset: UTF-8
      locale: zh_CN
      time_format: HH:mm:ss
      date_format: yyyy-MM-dd
      datetime_format: yyyy-MM-dd HH:mm:ss
      template_update_delay: 7200s
    cache: true
    template-loader-path: file:////usr/local/template,classpath:/templates/
  ## 邮箱配置
  mail:
    host: smtp.qq.com
    password: lxshegkzfvnjbgah
    username: ergehenmeng@qq.com
    properties:
      mail.from: ergehenmeng@qq.com
  ## mq配置
  rabbitmq:
    listener:
      simple:
        prefetch: 1
        acknowledge-mode: auto
        max-concurrency: 10

# mybatis配置
mybatis-plus:
  mapper-locations:
    - classpath*:mapper/**/*.xml
  type-enums-package: com.eghm.common.enums.ref
  type-aliases-package: com.eghm.model.dto;com.eghm.model.vo
system:
  ali-pay:
    notify-host: https://localhost:8080
    pay-notify-url: /notify/ali/pay
    refund-notify-url: /notify/ali/refund
  wechat:
    notify-host: https://localhost:8080
    pay-notify-url: /notify/weChat/pay
    refund-notify-url: /notify/weChat/refund