server:
  port: 10010
spring:
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      timeout: 30s
      database: 5
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:p6spy:mysql://127.0.0.1:3306/base_project?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC&tinyInt1isBit=false
    username: root
    password: root
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    hikari:
      connection-test-query: select 'X'
      maximum-pool-size: 100
      minimum-idle: 5
  mail:
    host: smtp.qq.com
    password: wahdqqmlznmhbcae
    username: ergehenmeng@qq.com
    port: 465
    properties:
      ## 邮件发送者,遵循 RFC822 标准
      mail.from: =?UTF-8?B?6L+Q6JCl5Zui6Zif?= <ergehenmeng@qq.com>
      mail.smtp.auth: true
      mail.smtp.ssl.enable: true
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    listener:
      simple:
        prefetch: 1
        acknowledge-mode: manual
        max-concurrency: 10
        retry:
          initial-interval: 10000
          enabled: true
          max-interval: 30000
system:
  # 全局文件上传路径
  upload-path: D://file
  wechat:
    pay:
      notify-host: https://localhost:8080
    ma:
      version: trial
  api:
    mock-token: d3df31f547654e2185be6dccbd155700
management:
  endpoint:
    env:
      enabled: true
    info:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,info,env,metrics,loggers,logfile,prometheus,beans