server:
  port: 10010
spring:
  application:
    name: webapp
  profiles:
    active: dev
  main:
    web-application-type: servlet
  output:
    ansi:
      enabled: detect
  jackson:
    time-zone: GMT+8
    deserialization:
      read-unknown-enum-values-as-null: true
  mvc:
    throw-exception-if-no-handler-found: true
  freemarker:
    check-template-location: false
    content-type: text/html
    settings:
      number_format: 0.##
      default_encoding: UTF-8
      output_encoding: UTF-8
      url_escaping_charset: UTF-8
      locale: zh_CN
      time_format: HH:mm:ss
      date_format: yyyy-MM-dd
      datetime_format: yyyy-MM-dd HH:mm:ss
      template_update_delay: 7200s
    cache: true
    template-loader-path: file:////usr/local/template,classpath:/templates/


# mybatis配置
mybatis-plus:
  mapper-locations:
    - classpath*:mapper/**/*.xml
  type-aliases-package: com.eghm.model.dto;com.eghm.model.vo;com.eghm.handler.mysql
  configuration:
    map-underscore-to-camel-case: true