GET http://localhost:10010/webapp/member/device/list
Channel: {{Channel}}
Token: {{Token}}

###

POST http://localhost:10010/webapp/member/device/unbind
Channel: {{Channel}}
Token: {{Token}}
Content-Type: application/json

{
  "id": ""
}