POST http://localhost:10010/webapp/feedback/submit
Channel: {{Channel}}
Token: {{Token}}
Content-Type: application/json

{
  "feedbackType": 1,
  "content": "demoData",
  "deviceBrand": "demoData",
  "deviceModel": "demoData",
  "version": "demoData",
  "systemVersion": "demoData"
}