GET http://localhost:9090/webapp/homestay/listPage?page=1&pageSize=10&longitude=120.332212&latitude=30.322123&sortByPrice=1&startDate=2023-10-09&endDate=2023-10-12
Channel: {{Channel}}

###

GET http://localhost:9090/webapp/homestay/detail?id=1710940638564323330
Channel: {{Channel}}