GET http://localhost:9090/webapp/homestay/room/listPage?page=1&pageSize=10&homestayId=1710940638564323330
Channel: {{Channel}}

###

GET http://localhost:9090/webapp/homestay/room/detail?id=1710945465285529602
Channel: {{Channel}}

###

GET http://localhost:9090/webapp/homestay/room/priceList?id=1710945465285529602
Channel: {{Channel}}

###