http://localhost:9090/webapp/item/listPage?page=1&pageSize=10
Channel: {{Channel}}

###
http://localhost:9090/webapp/item/detail?id=1763082719536959490
Channel: {{Channel}}

###
http://localhost:9090/webapp/item/recommend
Channel: {{Channel}}

###
http://localhost:9090/webapp/item/couponList?itemId=1763082719536959490
Channel: {{Channel}}
Token: {{Token}}

###
http://localhost:9090/webapp/item/couponScope?page=1&pageSize=10&sortBy=&couponId=1739535660503101442
Channel: {{Channel}}
Token: {{Token}}

###
POST http://localhost:9090/webapp/item/calcExpress
Channel: {{Channel}}
Content-Type: application/json

[{
  "storeId": "",
  "countyId": "",
  "orderList": [{
    "itemId": "",
    "skuId": "",
    "num": 1
  }]
}]