POST http://localhost:9090/webapp/login/sendSms
Content-Type: application/json; charset=utf-8
Channel: {{Channel}}

{
  "mobile": "13136113695"
}
###

POST http://localhost:9090/webapp/login/mobile
Content-Type: application/json; charset=utf-8
Channel: {{Channel}}

{
  "mobile": "13136113695",
  "smsCode": "9842"
}