POST http://localhost:10010/webapp/lottery/handle
Channel: {{Channel}}
Content-Type: application/json
Token: {{Token}}

{
  "id": 1937436344885579777
}


### 详情
http://localhost:10010/webapp/lottery/detail?id=1937416219457404929
Channel: {{Channel}}
Token: {{Token}}


### 抽奖记录
http://localhost:10010/webapp/lottery/logPage?page=1&pageSize=10
Channel: {{Channel}}
Token: {{Token}}
###