http://localhost:9090/webapp/member/notice/listPage?page=1&pageSize=10
Channel: {{Channel}}
Token: {{Token}}


###

POST http://localhost:9090/webapp/member/notice/delete
Channel: {{Channel}}
Token: {{Token}}
Content-Type: application/json

{
  "id": 123123
}

###

POST http://localhost:9090/webapp/member/notice/markRead
Channel: {{Channel}}
Token: {{Token}}
Content-Type: application/json

{
  "id": 123123
}

###