POST http://localhost:9090/webapp/member/coupon/receive
Channel: {{Channel}}
Content-Type: application/json
Token: {{Token}}

{
  "couponId": 1739535660503101442
}

###
GET http://localhost:9090/webapp/member/coupon/listPage?page=1&pageSize=10
Channel: {{Channel}}
Token: {{Token}}

###
GET http://localhost:9090/webapp/member/coupon/choose?id=
Channel: {{Channel}}
Token: {{Token}}