POST http://localhost:9090/webapp/member/signIn
Channel: {{Channel}}
Token: {{Token}}
Content-Type: application/json


###
GET http://localhost:9090/webapp/member/getSignIn
Channel: {{Channel}}
Token: {{Token}}


###
GET http://localhost:9090/webapp/member/my
Channel: {{Channel}}
Token: {{Token}}


###
GET http://localhost:9090/webapp/member/invitePage?page=1&pageSize=10
Channel: {{Channel}}
Token: {{Token}}


###
POST http://localhost:9090/webapp/member/edit
Channel: {{Channel}}
Token: {{Token}}
Content-Type: application/json

{
  "avatar": "http://localhost:9002/avatar.png",
  "nickName": "二哥很猛",
  "sex": 1
}