GET http://localhost:10010/webapp/merchant/authMobile?jsCode=1714920214586322945&authCode=123123
Channel: {{Channel}}


###
POST http://localhost:10010/webapp/merchant/binding
Channel: {{Channel}}
Content-Type: application/json
Token: {{Token}}

{
  "authCode": "",
  "mobile": "",
  "openId": ""
}
