POST http://localhost:10010/webapp/order/evaluation/create
Channel: {{Channel}}
Content-Type: application/json
Token: {{Token}}

{}
###

http://localhost:10010/webapp/order/evaluation/count?id=12
Channel: {{Channel}}


###

http://localhost:10010/webapp/order/evaluation/listPage?page=1&pageSize=10&productId=12&queryType=3
Channel: {{Channel}}


###