POST http://localhost:10010/webapp/order/ticket/create
Channel: {{Channel}}
Content-Type: application/json
Token: {{Token}}

{
  "ticketId": 1713787820047183874,
  "mobile": "13136113294",
  "num": 1,
  "visitDate": "2023-12-12",
  "remark": "少点套路"
}

###

POST http://localhost:10010/webapp/order/item/create
Channel: {{Channel}}
Content-Type: application/json
Token: {{Token}}

{
  "addressId": 1722175064609751041,
  "remark": "订单备注",
  "itemList": [{
    "itemId": 1717389387411066882,
    "skuId": 1717389387478175745,
    "num": 2
  }]
}



###

POST http://localhost:10010/webapp/order/homestay/create
Channel: {{Channel}}
Content-Type: application/json
Token: {{Token}}

{
  "roomId": 1714565181759881218,
  "num": 1,
  "mobile": "13136113453",
  "nickName": "二哥",
  "startDate": "2023-11-25",
  "endDate": "2023-11-26",
  "remark": "备注信息",
  "visitorList": [{
    "idCard": "620622196011141794",
    "memberName": "山邦家"
  },{
    "idCard": "150301196310204723",
    "memberName": "吕佳园"
  },{
    "idCard": "211422197202046042",
    "memberName": "从君菁"
  }]
}

###

POST http://localhost:10010/webapp/order/line/create
Channel: {{Channel}}
Content-Type: application/json
Token: {{Token}}

{
  "lineId": 1714916427083575297,
  "mobile": "13322231231",
  "nickName": "二哥很猛",
  "configDate": "2023-12-11",
  "num": 3,
  "visitorList": [{
    "memberName": "xxs",
    "idCard": "350522196302141849"
  }, {
    "memberName": "xxs",
    "idCard": "610825198401208947"
  }, {
    "memberName": "xxs",
    "idCard": "53082219660409737X"
  }],
  "remark": "备注信息"
}
###

POST http://localhost:10010/webapp/order/voucher/create
Channel: {{Channel}}
Content-Type: application/json
Token: {{Token}}

{
  "voucherId": 1716688620773548034,
  "num": 1,
  "nickName": "恩格",
  "mobile": "13433212312",
  "remark": "备注信息"
}

###

POST http://localhost:10010/webapp/order/venue/create
Channel: {{Channel}}
Content-Type: application/json
Token: {{Token}}

{
  "venueSiteId": 1760924119553056770,
  "phaseList": [1760952249583960070],
  "nickName": "钓鱼佬",
  "mobile": "13433212312",
  "remark": "备注信息"
}


###

POST http://localhost:10010/webapp/order/pay
Channel: {{Channel}}
Content-Type: application/json
Token: {{Token}}

{
  "orderNo": "",
  "buyerId": "",
  "tradeType": ""
}

###

POST http://localhost:10010/webapp/order/ticket/refundApply
Channel: {{Channel}}
Content-Type: application/json
Token: {{Token}}

{
  "orderNo": "MP1742099655827591170",
  "num": 1,
  "applyAmount": "60.00",
  "reason": "不想去了"
}

###

POST http://localhost:10010/webapp/order/line/refundApply
Channel: {{Channel}}
Content-Type: application/json
Token: {{Token}}

{
  "orderNo": "",
  "buyerId": "",
  "tradeType": ""
}

###

POST http://localhost:10010/webapp/order/homestay/refundApply
Channel: {{Channel}}
Content-Type: application/json
Token: {{Token}}

{
  "orderNo": "",
  "buyerId": "",
  "tradeType": ""
}

###

POST http://localhost:10010/webapp/order/voucher/refundApply
Channel: {{Channel}}
Content-Type: application/json
Token: {{Token}}

{
  "orderNo": "",
  "buyerId": "",
  "tradeType": ""
}


###

POST http://localhost:10010/webapp/order/item/refundApply
Channel: {{Channel}}
Content-Type: application/json
Token: {{Token}}

{
  "orderNo": "",
  "buyerId": "",
  "tradeType": ""
}

###
GET http://localhost:10010/webapp/order/refresh?id=
Channel: {{Channel}}


###