POST http://localhost:10010/webapp/order/ticket/create
Channel: {{Channel}}
Content-Type: application/json
Token: {{Token}}

{
  "ticketId": 1819246887106777090,
  "mobile": "13136113294",
  "num": 1,
  "visitDate": "2025-05-12",
  "remark": "少点套路",
  "visitorList": [{
    "memberName": "彭铭",
    "idCard": "332722197111166924"
  }]
}

###

POST http://localhost:10010/webapp/order/item/create
Channel: {{Channel}}
Content-Type: application/json
Token: {{Token}}

{
  "addressId": 1768538178234945537,
  "itemList": [{
    "storeId": 1818206459138408449,
    "remark": "备注信息",
    "skuList": [{
      "itemId": 1820275686682574850,
      "num": 1,
      "skuId": 1820275686812598274
    }]
  }]
}



###

POST http://localhost:10010/webapp/order/homestay/create
Channel: {{Channel}}
Content-Type: application/json
Token: {{Token}}

{
  "roomId": 1818896979821719553,
  "num": 2,
  "mobile": "13136113453",
  "nickName": "二哥",
  "startDate": "2025-05-27",
  "endDate": "2025-05-29",
  "remark": "备注信息",
  "visitorList": [{
    "idCard": "620622196011141794",
    "memberName": "山邦家"
  },{
    "idCard": "211422197202046042",
    "memberName": "从君菁"
  }]
}

###

POST http://localhost:10010/webapp/order/line/create
Channel: {{Channel}}
Content-Type: application/json
Token: {{Token}}

{
  "lineId": 1818471772440133633,
  "mobile": "13322231231",
  "nickName": "二哥很猛",
  "configDate": "2025-05-26",
  "num": 1,
  "visitorList": [{
    "memberName": "xxs",
    "idCard": "350522196302141849"
  }],
  "remark": "备注信息"
}
###

POST http://localhost:10010/webapp/order/voucher/create
Channel: {{Channel}}
Content-Type: application/json
Token: {{Token}}

{
  "voucherId": 1818851629819858945,
  "num": 1,
  "nickName": "恩格",
  "mobile": "13433212312",
  "remark": "备注信息"
}

###

POST http://localhost:10010/webapp/order/venue/create
Channel: {{Channel}}
Content-Type: application/json
Token: {{Token}}

{
  "venueSiteId": 1920293426334121985,
  "phaseList": [1920293794774368258,1920293794774368259],
  "nickName": "钓鱼佬",
  "mobile": "13433212312",
  "remark": "备注信息"
}


###

POST http://localhost:10010/webapp/order/pay
Channel: {{Channel}}
Content-Type: application/json
Token: {{Token}}

{
  "orderNo": "",
  "buyerId": "",
  "tradeType": "ZERO_PAY"
}

###

POST http://localhost:10010/webapp/order/ticket/refundApply
Channel: {{Channel}}
Content-Type: application/json
Token: {{Token}}

{
  "orderNo": "MP1742099655827591170",
  "num": 1,
  "applyAmount": "60.00",
  "reason": "不想去了"
}

###

POST http://localhost:10010/webapp/order/line/refundApply
Channel: {{Channel}}
Content-Type: application/json
Token: {{Token}}

{
  "orderNo": "",
  "buyerId": "",
  "tradeType": ""
}

###

POST http://localhost:10010/webapp/order/homestay/refundApply
Channel: {{Channel}}
Content-Type: application/json
Token: {{Token}}

{
  "orderNo": "",
  "buyerId": "",
  "tradeType": ""
}

###

POST http://localhost:10010/webapp/order/voucher/refundApply
Channel: {{Channel}}
Content-Type: application/json
Token: {{Token}}

{
  "orderNo": "",
  "buyerId": "",
  "tradeType": ""
}


###

POST http://localhost:10010/webapp/order/item/refundApply
Channel: {{Channel}}
Content-Type: application/json
Token: {{Token}}

{
  "orderNo": "",
  "buyerId": "",
  "tradeType": ""
}

###
GET http://localhost:10010/webapp/order/refresh?id=
Channel: {{Channel}}


###