GET http://localhost:9090/webapp/restaurant/listPage?page=1&pageSize=10&longitude=120.034411&latitude=30.234234
Channel: {{Channel}}
###

GET http://localhost:9090/webapp/restaurant/detail?id=1716687615256272898
Channel: {{Channel}}

