GET http://localhost:10010/webapp/scenic/listPage?page=1&pageSize=10&queryName=
Channel: {{Channel}}
###

GET http://localhost:10010/webapp/scenic/detail?scenicId=1712041763678035970
Channel: {{Channel}}


###

GET http://localhost:10010/webapp/scenic/ticket/detail?id=1712044044993486850
Channel: {{Channel}}
###