POST http://localhost:10010/webapp/shopping/cart/add
Content-Type: application/json
Channel: {{Channel}}
Token: {{Token}}

{
  "quantity": 2,
  "skuId": 1923191705695338504,
  "itemId": 1923191705565315074,
  "salePrice": 0
}
###

GET http://localhost:10010/webapp/shopping/cart/list
Channel: {{Channel}}
Token: {{Token}}

###

POST http://localhost:10010/webapp/shopping/cart/delete
Channel: {{Channel}}
Token: {{Token}}
Content-Type: application/json

{
  "ids": [
    1927604480878473218
  ]
}
###

POST http://localhost:10010/webapp/shopping/cart/quantity
Channel: {{Channel}}
Token: {{Token}}
Content-Type: application/json

{
  "id": 1927604794100707329,
  "quantity": 3
}
###