GET http://localhost:10010/webapp/venue/listPage?page=1&pageSize=10&longitude=120.334211&latitude=30.264652
Channel: {{Channel}}

###
GET http://localhost:10010/webapp/venue/detail?id=1920291568467165186
Channel: {{Channel}}

###
GET http://localhost:10010/webapp/venue/siteList?id=1920291568467165186
Channel: {{Channel}}

###
GET http://localhost:10010/webapp/venue/priceList?venueSiteId=1920293426334121985&nowDate=2025-05-08
Channel: {{Channel}}