<?xml version="1.0" encoding="UTF-8"?>
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://maven.apache.org/POM/4.0.0"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/maven-v4_0_0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <artifactId>parent</artifactId>
        <groupId>com.eghm</groupId>
        <version>1.0</version>
        <relativePath>../../pom.xml</relativePath>
    </parent>

    <name>manage-server</name>
    <artifactId>manage-server</artifactId>
    <packaging>jar</packaging>

    <dependencies>
        <dependency>
            <groupId>com.eghm</groupId>
            <artifactId>application-shared</artifactId>
        </dependency>
        <dependency>
            <groupId>com.eghm</groupId>
            <artifactId>application-system</artifactId>
        </dependency>
        <dependency>
            <groupId>com.eghm</groupId>
            <artifactId>application-member</artifactId>
        </dependency>
        <dependency>
            <groupId>com.eghm</groupId>
            <artifactId>application-operate</artifactId>
        </dependency>
        <dependency>
            <groupId>com.eghm</groupId>
            <artifactId>application-payment</artifactId>
        </dependency>
        <dependency>
            <groupId>com.eghm</groupId>
            <artifactId>infrastructure-shared</artifactId>
        </dependency>
        <dependency>
            <groupId>com.eghm</groupId>
            <artifactId>infrastructure-persistence</artifactId>
        </dependency>
        <dependency>
            <groupId>com.eghm</groupId>
            <artifactId>infrastructure-cache</artifactId>
        </dependency>
        <dependency>
            <groupId>com.eghm</groupId>
            <artifactId>infrastructure-message</artifactId>
        </dependency>
        <dependency>
            <groupId>com.eghm</groupId>
            <artifactId>infrastructure-integration</artifactId>
        </dependency>
        <dependency>
            <groupId>com.eghm</groupId>
            <artifactId>infrastructure-payment</artifactId>
        </dependency>
        <dependency>
            <groupId>com.eghm</groupId>
            <artifactId>web-core</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-websocket</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-actuator</artifactId>
        </dependency>
        <dependency>
            <groupId>org.flywaydb</groupId>
            <artifactId>flyway-core</artifactId>
        </dependency>
    </dependencies>

    <build>
        <finalName>${project.name}</finalName>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
            </plugin>
<!--            <plugin>
                <groupId>net.roseboy</groupId>
                <artifactId>classfinal-maven-plugin</artifactId>
                <version>1.2.1</version>
                <configuration>
                    &lt;!&ndash;#表示不需要密码&ndash;&gt;
                    <password>#</password>
                    <excludes>org.spring,org.apache</excludes>
                    <cfgfiles>application.yml,application-dev.yml</cfgfiles>
                    <packages>com.eghm</packages>
                    <libjars>application-1.0.jar</libjars>
                    <code>893A39CE44A3B9C2782E7536AE58D6E9D41D8CD98F00B204E9800998ECF8427ED41D8CD98F00B204E9800998ECF8427E</code>
                </configuration>
                <executions>
                    <execution>
                        <phase>package</phase>
                        <goals>
                            <goal>classFinal</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>-->
        </plugins>
    </build>

</project>
