<?xml version="1.0" encoding="UTF-8"?>
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://maven.apache.org/POM/4.0.0"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <artifactId>parent</artifactId>
        <groupId>com.eghm</groupId>
        <version>1.0</version>
        <relativePath>../../pom.xml</relativePath>
    </parent>

    <artifactId>infrastructure-shared</artifactId>
    <name>infrastructure-shared</name>
    <packaging>jar</packaging>

    <dependencies>
        <dependency>
            <groupId>com.eghm</groupId>
            <artifactId>application-shared</artifactId>
        </dependency>
        <dependency>
            <groupId>com.eghm</groupId>
            <artifactId>application-system</artifactId>
        </dependency>
        <dependency>
            <groupId>com.eghm</groupId>
            <artifactId>application-member</artifactId>
        </dependency>
        <dependency>
            <groupId>com.eghm</groupId>
            <artifactId>application-operate</artifactId>
        </dependency>
        <dependency>
            <groupId>com.eghm</groupId>
            <artifactId>application-payment</artifactId>
        </dependency>
        <dependency>
            <groupId>com.eghm</groupId>
            <artifactId>domain-shared</artifactId>
        </dependency>
        <dependency>
            <groupId>com.eghm</groupId>
            <artifactId>domain-system</artifactId>
        </dependency>
        <dependency>
            <groupId>com.eghm</groupId>
            <artifactId>domain-member</artifactId>
        </dependency>
        <dependency>
            <groupId>com.eghm</groupId>
            <artifactId>domain-operate</artifactId>
        </dependency>
        <dependency>
            <groupId>com.eghm</groupId>
            <artifactId>domain-payment</artifactId>
        </dependency>
        <dependency>
            <groupId>com.eghm</groupId>
            <artifactId>common</artifactId>
        </dependency>
        <dependency>
            <groupId>com.baomidou</groupId>
            <artifactId>mybatis-plus-spring-boot3-starter</artifactId>
        </dependency>
        <dependency>
            <groupId>com.baomidou</groupId>
            <artifactId>mybatis-plus-jsqlparser-4.9</artifactId>
        </dependency>
        <dependency>
            <groupId>org.redisson</groupId>
            <artifactId>redisson-spring-boot-starter</artifactId>
        </dependency>
        <dependency>
            <groupId>com.zaxxer</groupId>
            <artifactId>HikariCP</artifactId>
        </dependency>
        <dependency>
            <groupId>com.mysql</groupId>
            <artifactId>mysql-connector-j</artifactId>
            <scope>runtime</scope>
        </dependency>
        <dependency>
            <groupId>com.auth0</groupId>
            <artifactId>java-jwt</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-freemarker</artifactId>
        </dependency>
        <dependency>
            <groupId>com.aliyun.oss</groupId>
            <artifactId>aliyun-sdk-oss</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-mail</artifactId>
        </dependency>
        <dependency>
            <groupId>com.aliyun</groupId>
            <artifactId>dysmsapi20170525</artifactId>
        </dependency>
        <dependency>
            <artifactId>tea</artifactId>
            <groupId>com.aliyun</groupId>
        </dependency>
        <dependency>
            <groupId>com.tencentcloudapi</groupId>
            <artifactId>tencentcloud-sdk-java-sms</artifactId>
        </dependency>
        <dependency>
            <groupId>p6spy</groupId>
            <artifactId>p6spy</artifactId>
        </dependency>
        <dependency>
            <artifactId>spring-rabbit</artifactId>
            <groupId>org.springframework.amqp</groupId>
        </dependency>
        <dependency>
            <groupId>com.alipay.sdk</groupId>
            <artifactId>alipay-sdk-java</artifactId>
        </dependency>
        <dependency>
            <groupId>com.github.binarywang</groupId>
            <artifactId>weixin-java-miniapp</artifactId>
        </dependency>
        <dependency>
            <groupId>com.github.binarywang</groupId>
            <artifactId>weixin-java-mp</artifactId>
        </dependency>
        <dependency>
            <groupId>com.github.binarywang</groupId>
            <artifactId>weixin-java-pay</artifactId>
        </dependency>
        <dependency>
            <groupId>com.warrenstrange</groupId>
            <artifactId>googleauth</artifactId>
        </dependency>
    </dependencies>
</project>
