<?xml version="1.0" encoding="UTF-8"?>
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://maven.apache.org/POM/4.0.0"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <artifactId>parent</artifactId>
        <groupId>com.eghm</groupId>
        <version>1.0</version>
        <relativePath>../../pom.xml</relativePath>
    </parent>

    <artifactId>infrastructure-payment</artifactId>
    <name>infrastructure-payment</name>
    <packaging>jar</packaging>

    <dependencies>
        <dependency>
            <groupId>com.eghm</groupId>
            <artifactId>infrastructure-shared</artifactId>
        </dependency>
        <dependency>
            <groupId>com.eghm</groupId>
            <artifactId>infrastructure-integration</artifactId>
        </dependency>
        <dependency>
            <groupId>com.eghm</groupId>
            <artifactId>application-payment</artifactId>
        </dependency>
        <dependency>
            <groupId>com.eghm</groupId>
            <artifactId>domain-payment</artifactId>
        </dependency>
        <dependency>
            <groupId>com.alipay.sdk</groupId>
            <artifactId>alipay-sdk-java</artifactId>
        </dependency>
        <dependency>
            <groupId>com.github.binarywang</groupId>
            <artifactId>weixin-java-pay</artifactId>
        </dependency>
    </dependencies>
</project>
