<?xml version="1.0" encoding="UTF-8"?>
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://maven.apache.org/POM/4.0.0"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <artifactId>parent</artifactId>
        <groupId>com.eghm</groupId>
        <version>1.0</version>
    </parent>

    <artifactId>infrastructure</artifactId>
    <name>infrastructure</name>
    <packaging>pom</packaging>

    <modules>
        <module>infrastructure-shared</module>
        <module>infrastructure-persistence</module>
        <module>infrastructure-cache</module>
        <module>infrastructure-message</module>
        <module>infrastructure-integration</module>
        <module>infrastructure-payment</module>
    </modules>
</project>
