<?xml version="1.0" encoding="utf-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.eghm</groupId>
        <artifactId>parent</artifactId>
        <version>1.0</version>
        <relativePath>../../pom.xml</relativePath>
    </parent>
    
    <artifactId>integration-storage</artifactId>
    
    <dependencies>
        <dependency>
            <groupId>com.eghm</groupId>
            <artifactId>base-data</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>com.eghm</groupId>
            <artifactId>base-web</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>com.eghm</groupId>
            <artifactId>platform-config</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>io.minio</groupId>
            <artifactId>minio</artifactId>
        </dependency>
    </dependencies>
</project>
