GET localhost:8080/manage/version/listPage?page=1&pageSize=10
token: {{token}}

###

POST http://localhost:8080/manage/version/create
token: {{token}}
Content-Type: application/json

{
  "classify": "IOS",
  "state": 0,
  "version": "9.23",
  "forceUpdate": false,
  "url": "http://localhost:8080/manage/manage/download",
  "remark": "版本备注信息"
}


###

POST http://localhost:8080/manage/version/update
token: {{token}}
Content-Type: application/json

{
  "id": 1707305217112469506,
  "classify": "IOS",
  "state": 0,
  "version": "9.24",
  "forceUpdate": false,
  "url": "http://localhost:8080/manage/manage/download",
  "remark": "版本备注"
}
###

POST http://localhost:8080/manage/version/delete
token: {{token}}
Content-Type: application/json

{
  "id": 1707305217112469506
}