GET http://localhost:8080/manage/comment/listPage?page=1&pageSize=10
token: {{token}}

###
GET http://localhost:8080/manage/comment/report/listPage?page=1&pageSize=10&commentId=1764483232962777090
token: {{token}}

