GET http://localhost:8080/manage/coupon/listPage?page=1&pageSize=10
token: {{token}}

###

POST http://localhost:8080/manage/coupon/create
token: {{token}}
Content-Type: application/json

{
  "title": "年货节满100-30",
  "stock": 100,
  "maxLimit": 1,
  "mode": 1,
  "couponType": 1,
  "deductionValue": 30,
  "discountValue": 0,
  "useThreshold": 100,
  "useScope": 2,
  "storeId": 1717388362096668673,
  "startTime": "2022-01-01 00:00",
  "endTime": "2023-01-18 00:00",
  "useStartTime": "2023-01-01 00:00",
  "useEndTime": "2023-01-21 00:00",
  "instruction": "优惠券不折现,如果涉及退款,优惠券不返还. 部分退款时,按比例使用",
  "itemIds": [1717389387411066882]
}

###

POST http://localhost:8080/manage/coupon/update
token: {{token}}
Content-Type: application/json

{
  "id": 1610178152813809666,
  "title": "年货节满100-30",
  "stock": 888,
  "maxLimit": 2,
  "startTime": "2022-01-08 00:00",
  "endTime": "2023-01-18 00:00",
  "instruction": "优惠券不折现,如果涉及退款,优惠券不返还. 部分退款时,按比例使用",
  "productList": [{
    "productType": "product",
    "productIds": ["1608756388669820929"]
  }]
}

###

POST http://localhost:8080/manage/coupon/open
token: {{token}}
Content-Type: application/json

{
  "id": 1610178152813809666
}

###

GET http://localhost:8080/manage/coupon/select?id=1610178152813809666
token: {{token}}

###

POST http://localhost:8080/manage/coupon/close
token: {{token}}
Content-Type: application/json

{
  "id": 1610178152813809666
}

###

POST http://localhost:8080/manage/coupon/grant
token: {{token}}
Content-Type: application/json

{
  "memberIdList": [1],
  "couponId": 1610178152813809666,
  "num": 1
}