GET http://localhost:8080/manage/dept/list
token: {{token}}

###
POST http://localhost:8080/manage/dept/create
token: {{token}}
Content-Type: application/json

{
  "parentCode": "demoData",
  "title": "demoData",
  "remark": "demoData"
}

###
POST http://localhost:8080/manage/dept/update
token: {{token}}
Content-Type: application/json

{
  "parentCode": "demoData",
  "title": "demoData",
  "remark": "demoData"
}


###
POST http://localhost:8080/manage/dept/delete
token: {{token}}
Content-Type: application/json

{
  "id": 123123123123123
}

###
GET http://localhost:8080/manage/dept/select?id=1608668364569292801
token: {{token}}