GET http://localhost:8080/manage/group/booking/listPage?page=1&pageSize=10
token: {{token}}

###

POST http://localhost:8080/manage/group/booking/create
token: {{token}}
Content-Type: application/json

{
  "title": "团购商品",
  "itemId": 1717389387411066882,
  "startTime": "2024-02-26 15:10:14",
  "endTime": "2024-02-30 15:10:14",
  "num": 2,
  "expireTime": 1440,
  "skuList": [{
    "skuId": 1717389387478175745,
    "salePrice": 11,
    "discountPrice": 10
  }],
  "merchantId": 1707294309829128194
}

###
POST http://localhost:8080/manage/group/booking/update
token: {{token}}
Content-Type: application/json

{
  "id": 1762032666269491202,
  "title": "团购商品",
  "itemId": 1717389387411066882,
  "startTime": "2024-02-28 15:10:14",
  "endTime": "2024-03-11 15:10:14",
  "num": 2,
  "expireTime": 1440,
  "skuList": [{
    "skuId": 1717389387478175745,
    "salePrice": 11,
    "discountPrice": 8
  }]
}

###
GET http://localhost:8080/manage/group/booking/detail?id=1762032666269491202
token: {{token}}

###

POST http://localhost:8080/manage/group/booking/delete
token: {{token}}
Content-Type: application/json

{
  "id": 1762025129197453314
}