GET http://localhost:8080/manage/help/listPage?page=1&pageSize=10
token: {{token}}

###

POST http://localhost:8080/manage/help/create
token: {{token}}
Content-Type: application/json

{
  "ask": "问",
  "classify": 1,
  "answer": "答",
  "state": 1
}


###

POST http://localhost:8080/manage/help/update
token: {{token}}
Content-Type: application/json

{
  "id": 1735237599501037570,
  "ask": "问",
  "classify": 1,
  "answer": "答编辑",
  "state": 1
}

###

POST http://localhost:8080/manage/help/delete
token: {{token}}
Content-Type: application/json

{
  "id": 1735237599501037570
}