GET http://localhost:8080/manage/homestay/room/config/month?roomId=1607665031129849858&month=2022-12
token: {{token}}
###

POST http://localhost:8080/manage/homestay/room/config/setup
token: {{token}}
Content-Type: application/json

{
  "roomId": 1607665031129849858,
  "startDate": "2023-01-01",
  "endDate": "2023-01-31",
  "week": [1,2,3,4,5],
  "state": true,
  "stock": 10,
  "linePrice": 88,
  "salePrice": 38
}

###

POST http://localhost:8080/manage/homestay/room/config/update
token: {{token}}
Content-Type: application/json

{
  "roomId": 1607665031129849858,
  "configDate": "2022-12-09",
  "state": true,
  "stock": 20,
  "linePrice": 100,
  "salePrice": 68
}
