GET localhost:8080/manage/homestay/listPage?page=1&pageSize=10
token: {{token}}

###

POST http://localhost:8080/manage/homestay/create
token: {{token}}
Content-Type: application/json

{
  "title": "民宿名称",
  "level": 3,
  "provinceId": 110000,
  "cityId": 111000,
  "countyId": 111003,
  "detailAddress": "民宿详细地址",
  "longitude": 30.123434,
  "latitude": 120.7328431,
  "intro": "一句话简介..",
  "coverUrl": "https://localhost:8080/converUrl.png",
  "introduce": "民宿详细描述",
  "phone": "13233226975",
  "infrastructure": "1,2,3,4,5",
  "bathroom": "1,2,3,4,5",
  "kitchen": "3,2,3,4,1,3",
  "keyService": "1,3,4,2,1,",
  "tag": "123123,123123"
}

###

POST http://localhost:8080/manage/homestay/update
token: {{token}}
Content-Type: application/json

{
  "id": 1607659894533513218,
  "title": "民宿名称编辑",
  "level": 4,
  "provinceId": 110000,
  "cityId": 111000,
  "countyId": 111003,
  "detailAddress": "民宿详细地址编辑",
  "longitude": 30.123435,
  "latitude": 120.7328421,
  "intro": "一句话简介..编辑",
  "coverUrl": "https://localhost:8080/converUrl.png",
  "introduce": "民宿详细描述编辑",
  "phone": "13233226988",
  "infrastructure": "1,2,3,4,5",
  "bathroom": "1,2,3,4,5",
  "kitchen": "3,2,3,4,1,3",
  "keyService": "1,3,4,2,1,",
  "tag": "123123,123123"
}
###

POST http://localhost:8080/manage/homestay/shelves
token: {{token}}
Content-Type: application/json

{
  "id": "1607659894533513218"
}

###

POST http://localhost:8080/manage/homestay/unShelves
token: {{token}}
Content-Type: application/json

{
  "id": "1607659894533513218"
}