GET http://localhost:8080/manage/item/tag/list
Token: {{token}}


###
POST http://localhost:8080/manage/item/tag/create
Token: {{token}}
Content-Type: application/json

{
  "pid": "100",
  "title": "猫粮",
  "icon": "icon",
  "sort": 1
}

###
POST http://localhost:8080/manage/item/tag/delete
Token: {{token}}
Content-Type: application/json

{
  "id": 100100
}