GET http://localhost:8080/manage/express/template/list
Token: {{token}}

###
GET http://localhost:8080/manage/express/template/selectList
Token: {{token}}



###
POST http://localhost:8080/manage/express/template/create
Token: {{token}}
Content-Type: application/json

{
   "title": "模板名称",
   "chargeMode": 1,
   "regionList": [{
     "firstPart": 1,
     "firstPrice": 1,
     "nextPart": 1,
     "nextUnitPrice": 1,
     "regionCode": "110000",
     "regionName": "北京市"
   }]
}

###
POST http://localhost:8080/manage/express/template/update
Token: {{token}}
Content-Type: application/json

{
  "id": 1739935733154091009,
  "title": "北京市",
  "chargeMode": 1,
  "regionList": [{
    "firstPart": 1,
    "firstPrice": 1,
    "nextPart": 1,
    "nextUnitPrice": 1,
    "regionCode": "110101",
    "regionName": "东城区"
  }]
}

###
POST http://localhost:8080/manage/express/template/delete
Token: {{token}}
Content-Type: application/json

{
  "id": 1739935733154091009
}