GET http://localhost:8080/manage/limit/purchase/listPage?page=1&pageSize=10
token: {{token}}

####

POST http://localhost:8080/manage/limit/purchase/create
token: {{token}}
Content-Type: application/json

{
  "title": "显示购活动",
  "startTime": "2024-02-28 16:40:02",
  "endTime": "2024-03-26 16:40:02",
  "advanceHour": 1,
  "itemList": [{
    "itemId": 1717389387411066882,
    "skuList": [{
      "skuId": 1717389387478175745,
      "salePrice": 11,
      "discountPrice": 8
    }]
  }]
}

###

GET http://localhost:8080/manage/limit/purchase/detail?id=1762037301185196033
token: {{token}}
