GET http://localhost:8080/manage/line/listPage?page=1&pageSize=12
token: {{token}}


###

POST http://localhost:8080/manage/line/create
Content-Type: application/json
token: {{token}}

{
  "travelAgencyId": 12,
  "title": "杭州-上海(7日游)",
  "startProvinceId": 110000,
  "startCityId": 110100,
  "coverUrl": "https://localhost:8080/coverUrl.png",
  "virtualNum": 12,
  "duration": 1,
  "advanceDay": 1,
  "refundType": 1,
  "refundDescribe": "支持审核后退款",
  "introduce": "线路描述",
  "configList": [{
    "routeIndex": 1,
    "startPoint": "杭州",
    "endPoint": "上海",
    "trafficType": 1,
    "repast": 6,
    "depict": "今日活动描述"
  }]
}


###
POST  http://localhost:8080/manage/line/update
Content-Type: application/json
token: {{token}}

{
  "id": 1611287570074824706,
  "travelAgencyId": 12,
  "title": "杭州-上海(7日游)编辑",
  "startProvinceId": 110000,
  "startCityId": 110100,
  "coverUrl": "https://localhost:8080/coverUrl.png",
  "virtualNum": 12,
  "duration": 2,
  "advanceDay": 3,
  "refundType": 1,
  "refundDescribe": "支持审核后退款编辑",
  "introduce": "线路描述编辑",
  "configList": [{
    "routeIndex": 1,
    "startPoint": "杭州",
    "endPoint": "上海",
    "trafficType": 1,
    "repast": 6,
    "depict": "今日活动描述"
  },{
    "routeIndex": 2,
    "startPoint": "上海",
    "endPoint": "苏州",
    "trafficType": 1,
    "repast": 6,
    "depict": "第二日活动描述"
  }]
}

###

GET http://localhost:8080/manage/line/select?id=1607290976547602434
token: {{token}}

###
POST http://localhost:8080/manage/line/platformUnShelves
Content-Type: application/json
token: {{adminToken}}

{
  "id": 1607290976547602434
}

###
POST http://localhost:8080/manage/line/unShelves
Content-Type: application/json
token: {{token}}

{
  "id": 1607290976547602434
}

###
POST http://localhost:8080/manage/line/shelves
Content-Type: application/json
token: {{token}}

{
  "id": 1611287570074824706
}
###


POST http://localhost:8080/manage/line/delete
Content-Type: application/json
token: {{token}}

{
  "id": 1607290976547602434
}