GET http://localhost:8080/manage/member/listPage?page=1&pageSize=10
token: {{token}}


###

POST http://localhost:8080/manage/member/freeze
token: {{token}}
Content-Type: application/json

{
  "id": 1
}

###

POST http://localhost:8080/manage/member/unfreeze
token: {{token}}
Content-Type: application/json

{
  "id": 1
}

###
GET http://localhost:8080/manage/member/loginPage?page=1&pageSize=10
token: {{token}}

###
POST http://localhost:8080/manage/member/sendNotice
token: {{token}}
Content-Type: application/json

{
  "title": "demoData",
  "content": "demoDatasdfsdfsdf",
  "noticeType": "marketing",
  "memberIds": [
    1
  ]
}