GET http://localhost:8080/manage/merchant/listPage?page=1&pageSize=10
token: {{token}}

###

POST http://localhost:8080/manage/merchant/create
Content-Type: application/json
token: {{token}}

{
  "merchantName": "酒店商户",
  "type": 2,
  "nickName": "三哥很猛",
  "mobile": "13136113359",
  "userName": "sange123"
}

###

POST http://localhost:8080/manage/merchant/update
Content-Type: application/json
token: {{token}}

{
  "id": 1607653979663085569,
  "merchantName": "酒店商户编辑",
  "type": 3,
  "nickName": "三哥很猛编辑",
  "mobile": "13136113359"
}

###

POST http://localhost:8080/manage/merchant/lock
Content-Type: application/json
token: {{token}}

{
  "id": 1607653979663085569
}

###

POST http://localhost:8080/manage/merchant/unlock
Content-Type: application/json
token: {{token}}

{
  "id": 1607653979663085569
}