GET http://localhost:8080/manage/merchant/user/listPage?page=1&pageSize=10
token: {{token}}

###

POST http://localhost:8080/manage/merchant/user/create
Content-Type: application/json
token: {{token}}

{
  "nickName": "何晓燕",
  "mobile": "15888888888",
  "password": "hxy123456",
  "remark": "备注信息"
}

###
POST http://localhost:8080/manage/merchant/user/update
Content-Type: application/json
token: {{token}}

{
  "id": 1740198659672862722,
  "nickName": "何晓燕",
  "mobile": "15888888888",
  "password": "hxy@123456",
  "remark": "备注信息x"
}


###
POST http://localhost:8080/manage/merchant/user/lock
Content-Type: application/json
token: {{token}}

{
  "id": 1740198659672862722
}