GET http://localhost:8080/manage/merchant/listPage?page=1&pageSize=10
token: {{token}}

###

POST http://localhost:8080/manage/merchant/create
Content-Type: application/json
token: {{token}}

{
  "merchantName": "二哥的零售小店",
  "type": 8,
  "nickName": "二哥",
  "mobile": "13136115556",
  "enterpriseType": 1,
  "creditCode": "S00001",
  "businessLicenseUrl": "http://localhost:8080/manage/manage/download",
  "legalName": "FR",
  "legalIdCard": "132825196609182043",
  "legalUrl": "http://localhost:8080/manage/manage/download",
  "provinceId": 110000,
  "cityId": 110100,
  "countyId": 110101,
  "detailAddress": "地垄沟"
}

###

POST http://localhost:8080/manage/merchant/update
Content-Type: application/json
token: {{token}}

{
  "id": 1607653979663085569,
  "merchantName": "酒店商户编辑",
  "type": 3,
  "nickName": "三哥很猛编辑",
  "mobile": "13136113359"
}

###

POST http://localhost:8080/manage/merchant/lock
Content-Type: application/json
token: {{token}}

{
  "id": 1607653979663085569
}

###

POST http://localhost:8080/manage/merchant/unlock
Content-Type: application/json
token: {{token}}

{
  "id": 1607653979663085569
}