GET http://localhost:8080/manage/news/listPage?page=1&pageSize=10&code=LYGL
token: {{token}}

###
GET http://localhost:8080/manage/news/list
token: {{token}}


###
POST http://localhost:8080/manage/news/create
token: {{token}}
Content-Type: application/json

{
  "title": "大明山攻略",
  "code": "LYGL",
  "image": "cover.png",
  "content": "该水电费",
  "sort": 1
}

###
POST http://localhost:8080/manage/news/update
token: {{token}}
Content-Type: application/json

{
  "id": 1740655406086737921,
  "title": "大明山攻略",
  "code": "LYGL",
  "image": "cover.png",
  "content": "该水电费xx",
  "sort": 3
}

###
POST http://localhost:8080/manage/news/delete
token: {{token}}
Content-Type: application/json

{
  "id": 12
}


###
POST http://localhost:8080/manage/news/sort
token: {{token}}
Content-Type: application/json

{
  "id": 1740655406086737921,
  "sortBy": 12
}