GET http://localhost:8080/manage/news/config/listPage?page=1&pageSize=10
token: {{token}}

###
POST http://localhost:8080/manage/news/config/create
token: {{token}}
Content-Type: application/json

{
  "title": "旅游攻略",
  "code": "lygl",
  "includeTitle": true,
  "includeDepict": true,
  "includeImage": true,
  "includeContent": true,
  "includeVideo": false
}

###
POST http://localhost:8080/manage/news/config/update
token: {{token}}
Content-Type: application/json

{
  "id": 1740652775675060226,
  "title": "旅游攻略",
  "code": "LYGL",
  "includeTitle": true,
  "includeDepict": false,
  "includeImage": true,
  "includeContent": true,
  "includeVideo": false
}

###
POST http://localhost:8080/manage/news/config/delete
token: {{token}}
Content-Type: application/json

{
  "id": 1740652775675060226
}
