GET http://localhost:8080/manage/notice/template/listPage?page=1&pageSize=10
token: {{token}}

###
POST http://localhost:8080/manage/notice/template/update
token: {{token}}
Content-Type: application/json

{
  "id": 1,
  "title": "标题",
  "content": "内容",
  "remark": "备注"
}
