GET http://localhost:8080/manage/order/evaluation/listPage?page=1&pageSize=10
token: {{token}}

###
POST http://localhost:8080/manage/order/evaluation/audit
token: {{token}}
Content-Type: application/json

{
  "id": 1,
  "state": 1,
  "auditRemark": "demoData"
}