GET http://localhost:8080/manage/poi/point/listPage?page=1&pageSize=10
token: {{token}}

###
POST http://localhost:8080/manage/poi/point/create
token: {{token}}
Content-Type: application/json

{
  "title": "休息点",
  "areaCode": "WYS",
  "coverUrl": "cover.png",
  "typeId": 1742013039595442177,
  "longitude": 120.123213,
  "latitude": 30.849371,
  "detailAddress": "xxx",
  "introduce": "sdfsdfsdfsf"
}

###
POST http://localhost:8080/manage/poi/point/update
token: {{token}}
Content-Type: application/json

{
  "id": 1742018319699873794,
  "title": "休息点",
  "coverUrl": "cover.png",
  "typeId": 1742013039595442177,
  "areaCode": "WYS",
  "longitude": "120.1232130",
  "latitude": "30.8493710",
  "detailAddress": "xxxxxx",
  "introduce": "sdfsdfsdfsf"
}

###
POST http://localhost:8080/manage/poi/point/delete
token: {{token}}
Content-Type: application/json

{
  "id": 1742018319699873794
}

####
GET http://localhost:8080/manage/poi/point/select?id=1742018319699873794
token: {{token}}
