GET http://localhost:10086/manage/push/listPage?page=1&pageSize=10
token: {{token}}

###
POST http://localhost:10086/manage/push/update
token: {{token}}
Content-Type: application/json

{
  "id": 1,
  "title": "demoData",
  "content": "demoData",
  "state": true,
  "remark": "demoData"
}