GET http://localhost:8080/manage/redeem/code/listPage?page=1&pageSize=10
token: {{token}}


###
POST http://localhost:8080/manage/redeem/code/create
token: {{token}}
Content-Type: application/json

{
  "title": "兑换码名称",
  "state": 1,
  "startTime": "2023-12-14 13:27:19",
  "endTime": "2024-12-14 13:27:19",
  "amount": 100,
  "num": 20,
  "storeList": [{
    "storeId": 12,
    "productType": "item"
  }]
}

###
POST http://localhost:8080/manage/redeem/code/update
token: {{token}}
Content-Type: application/json

{
  "id": 1760870016600793089,
  "title": "兑换码名称编辑",
  "state": 1,
  "startTime": "2023-12-14 13:27:19",
  "endTime": "2024-12-14 13:27:19",
  "amount": 100,
  "num": 20,
  "storeList": [{
    "storeId": 12,
    "productType": "item"
  }]
}


###
GET http://localhost:8080/manage/redeem/code/select?id=1760870016600793089
token: {{token}}


###
GET http://localhost:8080/manage/redeem/code/scope?id=1760870016600793089
token: {{token}}

###
POST http://localhost:8080/manage/redeem/code/generate
token: {{token}}
Content-Type: application/json

{
  "id": 1760870016600793089
}

###
GET http://localhost:8080/manage/redeem/code/grant/listPage?page=1&pageSize=10&redeemCodeId=1760870016600793089
token: {{token}}