GET http://localhost:10086/manage/refund/log/listPage?page=1&pageSize=10
token: {{token}}

###
POST http://localhost:10086/manage/refund/log/audit
token: {{token}}
Content-Type: application/json

{
  "orderNo": "MP1742099655827591170",
  "refundId": 1742115517737418753,
  "state": 1,
  "refundAmount": 60,
  "auditRemark": "备注"
}