GET http://localhost:10086/manage/restaurant/listPage?page=1&pageSize=10
token: {{token}}
###

POST http://localhost:10086/manage/restaurant/create
token: {{token}}
Content-Type: application/json

{
  "title": "三哥的小吃店",
  "logoUrl": "https://localhost:10086/logoUrl.png",
  "coverUrl": "https://localhost:10086/coverUrl.png",
  "openTime": "09:00~20:00",
  "provinceId": 110000,
  "cityId": 110100,
  "countyId": 110102,
  "detailAddress": "我是详细地址",
  "longitude": "120.306943",
  "latitude": "30.332149",
  "phone": "13766889954",
  "introduce": "吃喝玩乐一起游"
}

###

POST http://localhost:10086/manage/restaurant/update
token: {{token}}
Content-Type: application/json

{
  "id": 1716687615256272898,
  "title": "哥的小吃店",
  "logoUrl": "https://localhost:10086/logoUrl.png",
  "coverUrl": "https://localhost:10086/coverUrl.png",
  "openTime": "09:00~20:00",
  "provinceId": 110000,
  "cityId": 110100,
  "countyId": 110102,
  "detailAddress": "我是详细地址Edit",
  "longitude": "120.306943",
  "latitude": "30.332149",
  "phone": "13766889954",
  "introduce": "吃喝玩乐一起游Edit"
}

###

POST http://localhost:10086/manage/restaurant/shelves
token: {{token}}
Content-Type: application/json

{
  "id": 1716687615256272898
}