GET http://localhost:8080/manage/scenic/ticket/listPage?page=1&pageSize=10
token: {{token}}

###
POST http://localhost:8080/manage/scenic/ticket/create
token: {{token}}
Content-Type: application/json

{
  "scenicId": 1712041763678035970,
  "title": "全票",
  "category": 1,
  "coverUrl": "http://localhost:8080/ticket/coverUrl.png",
  "linePrice": 80,
  "salePrice": 60,
  "advanceDay": 1,
  "quota": 1,
  "startDate": "2022-12-20",
  "endDate": "2023-03-31",
  "stock": 100,
  "introduce": "门票详细介绍-门票包含XX",
  "useScope": 31,
  "verificationType": 1,
  "refundType": 0,
  "realBuy": false
}

###
POST http://localhost:8080/manage/scenic/ticket/update
token: {{token}}
Content-Type: application/json

{
  "id": 1712044044993486850,
  "scenicId": 1712041763678035970,
  "title": "联票",
  "category": 1,
  "coverUrl": "http://localhost:8080/ticket/coverUrl.png",
  "linePrice": 100,
  "salePrice": 68,
  "advanceDay": 1,
  "quota": 1,
  "startDate": "2022-12-20",
  "endDate": "2024-03-31",
  "stock": 100,
  "introduce": "门票详细介绍-门票包含XX编辑",
  "useScope": 31,
  "verificationType": 1,
  "refundType": 0,
  "realBuy": false
}

###

GET http://localhost:8080/manage/scenic/ticket/select?id=1608697527963467777
token: {{token}}

###
POST http://localhost:8080/manage/scenic/ticket/shelves
token: {{token}}
Content-Type: application/json

{
  "id": 1712044044993486850
}

###
POST http://localhost:8080/manage/scenic/ticket/unShelves
token: {{token}}
Content-Type: application/json

{
  "id": 1608697527963467777
}

###
POST http://localhost:8080/manage/scenic/ticket/platformUnShelves
token: {{adminToken}}
Content-Type: application/json

{
  "id": 1608697527963467777
}

###
POST http://localhost:8080/manage/scenic/ticket/delete
token: {{token}}
Content-Type: application/json

{
  "id": 1608697527963467777
}