GET http://localhost:10086/manage/sms/template/listPage?page=1&pageSize=10
token: {{token}}

###

POST http://localhost:10086/manage/sms/template/update
token: {{token}}
Content-Type: application/json

{
  "id": 1,
  "content": "您正在登陆EGHM平台，短信验证码：{0}。如非本人操作，请忽略此短信",
  "remark": "登陆发送验证码模板"
}

###