GET http://localhost:10086/manage/statistics/register?startDate=2022-12-12&endDate=2024-12-12
token: {{token}}

###
GET http://localhost:10086/manage/statistics/dayRegister?startDate=2022-12-12&endDate=2024-12-12
token: {{token}}

###
GET http://localhost:10086/manage/statistics/order?startDate=2022-12-12&endDate=2024-12-12
token: {{token}}

###
GET http://localhost:10086/manage/statistics/dayOrder?startDate=2022-12-12&endDate=2024-12-12
token: {{token}}

###
GET http://localhost:10086/manage/statistics/visit?startDate=2022-12-12&endDate=2024-12-12
token: {{token}}

###
GET http://localhost:10086/manage/statistics/collect?startDate=2022-12-12&endDate=2024-12-12&collectType=1
token: {{token}}


###
GET http://localhost:10086/manage/statistics/append?startDate=2022-12-12&endDate=2024-12-12
token: {{token}}


###
GET http://localhost:10086/manage/statistics/cart?startDate=2022-12-12&endDate=2024-12-12
token: {{token}}
