GET http://localhost:8080/manage/venue/order/listPage?page=1&pageSize=10&endDate=2023-11-11
Token: {{token}}

###

GET http://localhost:8080/manage/venue/order/detail?orderNo=YY1764898457887834113
Token: {{token}}