GET http://localhost:10086/manage/venue/site/listPage?page=1&pageSize=10&venueId=1760922048632233986
token: {{token}}

###

POST http://localhost:10086/manage/venue/site/create
token: {{token}}
Content-Type: application/json

{
  "title": "羽毛球-B2馆",
  "coverUrl": "coverUrl.png",
  "venueId": 1760922048632233986
}

###

POST http://localhost:10086/manage/venue/site/update
token: {{token}}
Content-Type: application/json

{
  "id": 1760924119553056770,
  "title": "羽毛球-B-1A",
  "coverUrl": "coverUrl.png",
  "venueId": 1760922048632233986
}

###

GET http://localhost:10086/manage/venue/site/select?id=1760924119553056770
token: {{token}}

###

GET http://localhost:10086/manage/venue/site/priceList?venueSiteId=1760924119553056770&nowDate=2024-02-23
token: {{token}}

###

POST http://localhost:10086/manage/venue/site/shelves
token: {{token}}
Content-Type: application/json

{
  "id": 1760924119553056770
}

###

POST http://localhost:10086/manage/venue/site/unShelves
token: {{token}}
Content-Type: application/json

{
  "id": 1760924119553056770
}

###

POST http://localhost:10086/manage/venue/site/platformUnShelves
token: {{token}}
Content-Type: application/json

{
  "id": 1760924119553056770
}

###

POST http://localhost:10086/manage/venue/site/price/setup
token: {{token}}
Content-Type: application/json

{
  "venueSiteId": 1760924119553056770,
  "startDate": "2024-03-20",
  "endDate": "2024-04-18",
  "week": [
    1, 2, 3, 4, 5
  ],
  "priceList": [{
    "startTime": "09:00",
    "endTime": "10:00",
    "price": 10
  }, {
    "startTime": "10:00",
    "endTime": "11:00",
    "price": 12
  }, {
    "startTime": "11:00",
    "endTime": "12:00",
    "price": 14
  }, {
    "startTime": "14:00",
    "endTime": "15:00",
    "price": 20
  }, {
    "startTime": "15:00",
    "endTime": "16:00",
    "price": 22
  }, {
    "startTime": "16:00",
    "endTime": "17:00",
    "price": 25
  }]
}