GET http://localhost:8080/manage/venue/listPage?page=1&pageSize=10
token: {{token}}

###

POST http://localhost:8080/manage/venue/create
token: {{token}}
Content-Type: application/json

{
  "title": "场馆名称",
  "venueType": 1,
  "coverUrl": "cover_url",
  "openTime": "12:00-18:00",
  "provinceId": 1,
  "cityId": 1,
  "countyId": 1,
  "detailAddress": "demoData",
  "longitude": 30,
  "latitude": 30,
  "telephone": "13133332222",
  "introduce": "demoData"
}

###

POST http://localhost:8080/manage/venue/update
token: {{token}}
Content-Type: application/json

{
  "id": 1760922048632233986,
  "title": "场馆名称BG",
  "venueType": 1,
  "coverUrl": "cover_url",
  "openTime": "12:00-18:00",
  "provinceId": 1,
  "cityId": 1,
  "countyId": 1,
  "detailAddress": "demoData",
  "longitude": 30,
  "latitude": 30,
  "telephone": "13133332222",
  "introduce": "demoData"
}


###

GET http://localhost:8080/manage/venue/select?id=1760922048632233986
token: {{token}}

###

POST http://localhost:8080/manage/venue/shelves
token: {{token}}
Content-Type: application/json

{
  "id": 1760922048632233986
}
###

POST http://localhost:8080/manage/venue/unShelves
token: {{token}}
Content-Type: application/json

{
  "id": 1760922048632233986
}


###

POST http://localhost:8080/manage/venue/platformUnShelves
token: {{token}}
Content-Type: application/json

{
  "id": 1760922048632233986
}
