GET http://localhost:10086/manage/verify/listPage?page=1&pageSize=10
token: {{token}}

###
GET http://localhost:10086/manage/verify/scan?verifyNo=MP12312323
token: {{token}}

###
POST http://localhost:10086/manage/verify/verify
token: {{token}}
Content-Type: application/json

{
  "orderNo": "MP12312323",
  "visitorList": [
    1
  ],
  "remark": "xxx"
}